apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-marketplace

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - elasticsearch-statefulset.yaml
  - kafka-statefulset.yaml
  - publishing-service.yaml
  - discovery-service.yaml
  - consumption-service.yaml
  - admin-service.yaml
  - monitoring.yaml
  - istio-gateway.yaml
  - storage-class.yaml

commonLabels:
  app.kubernetes.io/part-of: llm-marketplace
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - init.sql=../../sql/init.sql
